

name: pulumi-esc-read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  esc_read:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve values
        uses: jaxxstorm/action-pulumi-esc@main
        id: esc
        with:
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          organization: arun-test
          environment: AwsOIDC
          keys: '$.properties.environmentVariables.value.AWS_ACCESS_KEY_ID.value'

      - name: Use the output
        run: |
            echo "The extracted values are: ${{ steps.esc.outputs.result }}"
