# ...

name: pulumi-esc-read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    
    runs-on: ubuntu-latest

    steps:
        - name: Retrieve values
        uses: jaxxstorm/action-pulumi-esc@main
        id: esc
        with:
            access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            organization: aruntest
            environment: AwsOIDC
            keys: '$.properties.environmentVariables.value.EXAMPLE_SETTING.value'
        - name: Use the output
        run: |
            echo "The extracted values are: ${{ steps.esc.outputs.result }}"